### PR TITLE
Use first and second instead of _1 and _2

### PR DESCRIPTION
**Pull request by paf31**
This seems cleaner given we have a `Strong` constraint anyway. I think we can do the same with `Left` and `Right`. In fact, I think we can deprecate `_1` and `_2`.

### CODE REVIEW

**Comment by garyb** [comment]
:+1: Should we just get rid of these (and `Either`'s) entirely then?

**Comment by garyb** [comment]
Although there is perhaps something to be said for keeping them as a better fit for the "lens DSL", like `_SomePrism <<< _Left <<< _Whatever` perhaps fits better than `_SomePrism <<< left <<< _Whatever`? I don't feel strongly either way.

**Comment by paf31** [comment]
I've added `left` and `right`. I think I'll keep the existing versions, but reexport the nicer names. 

These functions probably give a decent intuition for how profunctor lenses/prisms work, so it'd be good to encourage their use IMO.

**Comment by paf31** [comment]
Even with the reexports, this can be a minor change right?

**Comment by garyb** [comment]
I think so... kinda. Any change in a module's exports is potentially a breaking change because we allow open import lists. That's one of the reasons I've started being explicit everywhere even in cases in the core libraries where it's unlikely to be a problem.

But generally we've been ignoring that and additions are just counted as as patch versions, so :+1:

**Pull request merged**
