### PR TITLE
Add `ifolded` and `imapped` (closes #147)

### PR DESCRIPTION
**Pull request by twhitehead**
**Description of the change**

This adds the `ifolded` and `imapped` functions to provide an `IndexedFold` and an `IndexedSetter` for all instances of `FoldableWithIndex` and `FunctorWithIndex` as `itraversed` provides an `IndexedTraversal` for all instances of `TraversableWithIndex`

---

**Checklist:**

- [X] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [X] Linked any existing issues or proposals that this pull request should close
- [X] Updated or added relevant documentation in the README and/or documentation directory
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by garyb** [comment]
This PR failure is nothing to do with you, but would you mind updating the package set ref from `prepare-0.15` to `psc-0.15.15-20240829` or something recent like that? That should fix it!

**Comment by twhitehead** [comment]
Thanks. Noticed my layout, with respect to line breaks, didn't exactly follow that of the existing file too, so fixed that as well.

**Comment by twhitehead** [comment]
@garyb Seems to still be dying on some CI build item unrelated to this pull request
```
...

purescript-refs#6.0.0 bower_components/purescript-refs
├── purescript-effect#4.0.0
└── purescript-prelude#6.0.1
* Building project in /home/runner/work/purescript-profunctor-lenses/purescript-profunctor-lenses
* Unable to parse the version from psa. (It was: v0.9.0)
* Please check that the right executable is on your PATH.
Invalid option `--censor-lib'

Usage: purs COMMAND

  The PureScript compiler and tools
* ERROR: Subcommand terminated with exit code 1
```
Any ideas? It built fine on my machine using `spago` once I converted `spago.dhall` to `spago.yaml`.

**Comment by garyb** [comment]
Hmm, yeah this is a `pulp` and `psa` build related thing, but I'm not really sure why it's a problem now.

I think changing the [CI line](https://github.com/purescript-contrib/purescript-profunctor-lenses/blob/cbf678c5fa324d6704aa10c58c89715cae7cb20c/.github/workflows/ci.yml#L46C11-L46C50):

```
npx pulp build -- --censor-lib --strict
```
to just:
```
npx pulp build
```
should get it through.

**Comment by garyb** [comment]
Sorry, looks like you changed the wrong line there. It's not the `spago` build that is problematic, it's the usage of `pulp` in the `Verify Bower & Pulp` task. Line 46 🙂.

I'd edit this myself to make the fix rather than subjecting you to the busywork, but I don't think I can because it's coming from your `main` branch.

**Comment by twhitehead** [comment]
Sorry about that. Hopefully I got it right this time. :crossed_fingers:

**Comment by garyb** [comment]
That did the trick, thanks!

**Pull request merged**
