### PR TITLE
Split Getter into Getter and AGetter - so Getter can easily compose

### PR DESCRIPTION
**Pull request by LiamGoodacre**
For https://github.com/purescript-contrib/purescript-profunctor-lenses/issues/85

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
Success:

```purescript
> foo = to (_ > 10)
> bar = to show
> baz = foo <<< bar
> :t baz
forall t18 t20 t21. Strong t20 => Bicontravariant t20 => t20 String t21 -> t20 Int t18

> view baz 3
"false"

> view baz 33
"true"
```

**Comment by LiamGoodacre** [comment]
Oh wait, that works with the original `to`/`view` too.
Looks like the issue is with the `Getter` synonym being too specific about the index to `Forget`.

**Comment by LiamGoodacre** [comment]
I think this is ready, unless anyone has any issues with it.

**Comment by LiamGoodacre** [comment]
This should be considered a breaking change.

**Comment by marick** [comment]
I continue to add documentation to the API, and I would be very happy to see an explanation of the "why" behind `AThing` and `Thing` that didn't assume knowledge of Haskell lenses.

**Comment by LiamGoodacre** [comment]
@marick I don't have a full explanation, but they are useful in situations where you want to pass optics around in data structures - constrained types don't play well being in non-function type arguments:
```purescript
baz :: forall t x . Category t => Identity (forall i . Category t => t i i) -> t x x
baz (Identity u) = u
```
The above fails to compile.

The representation of optics in this library uses various profunctor constraints.  If you, for example, tried to store one in a record, you will likely run into trouble.

**Pull request merged**
